server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: serkan
      password: root
      database: pribasDb
#      url: mongodb://localhost:27017/pribasDb
